<a href="https://colab.research.google.com/github/RajaeKrib/Numpy-Bootcamp/blob/main/Numpy_71_80_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

### Table of contents:
* [Import biblioteki](#0)
* [Exercise 71](#1)
* [Exercise 72](#2)
* [Exercise 73](#3)
* [Exercise 74](#4)
* [Exercise 75](#5)
* [Exercise 76](#6)
* [Exercise 77](#7)
* [Exercise 78](#8)
* [Exercise 79](#9)
* [Exercise 80](#10)

### <a name='0'></a> Import of libraries

In [ ]:
import numpy as np

np.random.seed(42)
np.__version__

'1.19.5'

### <a name='1'></a> Exercise 71
The following $ A $ array is given:
```
A = np.array([['id', 'price'],
              ['001', 14.99],
              ['002', 4.99],
              ['003', 7.99],
              ['004', 2.49],
              ['005', 1.49]])
```
From the second row of the $ A $ array, randomly shuffle the rows in the array.

__Tip:__ Use the _np.random.shuffle()_ function.


In [ ]:
A = np.array([['id', 'price'],
              ['001', 14.99],
              ['002', 4.99],
              ['003', 7.99],
              ['004', 2.49],
              ['005', 1.49]])

np.random.shuffle(A)
A

array([['id', 'price'],
       ['005', '1.49'],
       ['003', '7.99'],
       ['001', '14.99'],
       ['004', '2.49'],
       ['002', '4.99']], dtype='<U5')

### <a name='2'></a> Exercise 72
The following array $ A $ is given:

```
A = np.array([0.2, 0.15, 0.1, 0.3, 0.2, 0.05])
```
Return an array of indexes that will sort the array $ A $ in ascending order.

__Expected result:__

```
array([5, 2, 1, 0, 4, 3])
```
__Tip:__ Use the _np.argsort()_ function.


In [ ]:
A = np.array([0.2, 0.15, 0.1, 0.3, 0.2, 0.05])
np.argsort(A)

array([5, 2, 1, 0, 4, 3])

### <a name='3'></a> Exercise 73

The following array $ A $ is given:
```
A = np.random.randn(10, 8)
```
Round the values of this array to three decimal places.

__Tip:__ Use the function _np.round()_.


In [ ]:
A = np.random.randn(10, 8)
np.round(A, decimals=3)

array([[ 0.293,  0.897, -0.61 , -0.316, -1.482, -0.229,  0.963, -0.21 ],
       [-0.774, -0.36 ,  0.724, -0.256,  0.85 , -1.311, -0.87 , -0.507],
       [-1.31 ,  2.944, -1.096,  0.915, -0.666, -0.514,  0.301, -1.459],
       [-0.663, -0.146, -0.846, -0.822,  1.087,  1.005, -0.442, -0.084],
       [ 1.237, -1.426,  0.338,  1.975,  1.965, -1.94 , -0.763,  0.169],
       [-1.322, -0.668, -0.137,  1.401, -0.045,  0.217,  0.512,  0.543],
       [ 0.028, -1.197,  0.79 ,  0.431, -1.097, -0.682,  0.888,  0.605],
       [-0.72 , -0.27 , -0.143,  0.617,  1.249,  0.066,  1.169,  0.873],
       [ 0.206, -1.443, -1.028,  0.741, -1.711,  0.119,  1.   ,  0.152],
       [-0.601, -0.847,  0.816,  0.472, -0.285,  1.065,  0.854,  1.789]])

### <a name='4'></a> Exercise 74
Determine the roots of the polynomial:
* $W(x) = 4x^2 + 5x + 1$

Check the solution.

__Tip:__ Use the _np.roots()_ and _np.polyval()_ functions.

In [ ]:
np.polyval([4,5,1], np.roots([4,5,1]))

array([0., 0.])

### <a name='5'></a> Exercise 75
Determine the roots of polynomials:
* $Q(x) = 2x^3 + 4x^2 -5x + 1$
* $R(x) = 2x^3 -5x + 1$

__Tip:__ Use the _np.roots()_ function.


In [ ]:
Q = np.roots([2,4,-5,1])
R = np.roots([2,-5,1])

print(f'Q(x) roots are {Q}')
print(f'R(x) roots are {R}')

Q(x) roots are [-2.91610583  0.65388685  0.26221898]
R(x) roots are [2.28077641 0.21922359]


### <a name='6'></a> Exercise 76
Polynomials are given:
* $W(x) = 4x^2 + 5x + 1$
* $Q(x) = 2x^3 + 4x^2 -5x + 1$


In [ ]:
W = np.array([4, 5, 1])
Q = np.array([2, 4, -5, 1])

Perform:
* $ W (x) + Q (x) $

In [ ]:
np.polyadd(W, Q)

array([2, 8, 0, 2])

* $W(x) - Q(x)$


In [ ]:
np.polysub(W,Q)

array([-2,  0, 10,  0])

* $W(x) * Q(x)$


In [ ]:
np.polymul(W, Q)

array([  8,  26,   2, -17,   0,   1])

* $W(x) + 2Q(x)$

In [ ]:
np.polyadd(W, 2*Q)

array([ 4, 12, -5,  3])

### <a name='7'></a> Exercise 77
The array below is given:

```
A = np.array([[-4, 3, 0, 1, -5],
              [6, -4, -2, 1, 3]])
```
Use the sign function for the array $ A $. As a reminder, the function works as follows: returns -1 for negative values, zero for zero, and 1 for positive values.

__Expected result:__

```
array([[-1,  1,  0,  1, -1],
       [ 1, -1, -1,  1,  1]])
```
__Tip:__ Use the _np.sign()_ function.

In [ ]:
A = np.array([[-4, 3, 0, 1, -5],
              [6, -4, -2, 1, 3]])

np.sign(A)

array([[-1,  1,  0,  1, -1],
       [ 1, -1, -1,  1,  1]])

### <a name='8'></a> Exercise 78
Using the _np.arange()_ function, generate the following array:

```
array(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
       '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08',
       '2021-01-09', '2021-01-10', '2021-01-11', '2021-01-12',
       '2021-01-13', '2021-01-14', '2021-01-15', '2021-01-16',
       '2021-01-17', '2021-01-18', '2021-01-19', '2021-01-20',
       '2021-01-21', '2021-01-22', '2021-01-23', '2021-01-24',
       '2021-01-25', '2021-01-26', '2021-01-27', '2021-01-28',
       '2021-01-29', '2021-01-30', '2021-01-31'], dtype='datetime64[D]')
```


In [ ]:
np.arange('2021-01-01', '2021-02-01', dtype='datetime64[D]')

array(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
       '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08',
       '2021-01-09', '2021-01-10', '2021-01-11', '2021-01-12',
       '2021-01-13', '2021-01-14', '2021-01-15', '2021-01-16',
       '2021-01-17', '2021-01-18', '2021-01-19', '2021-01-20',
       '2021-01-21', '2021-01-22', '2021-01-23', '2021-01-24',
       '2021-01-25', '2021-01-26', '2021-01-27', '2021-01-28',
       '2021-01-29', '2021-01-30', '2021-01-31'], dtype='datetime64[D]')

### <a name='9'></a> Exercise 79

Using the _np.arange()_ function, generate the following array:

```
array([['2021-01', '2021-02', '2021-03'],
       ['2021-04', '2021-05', '2021-06'],
       ['2021-07', '2021-08', '2021-09'],
       ['2021-10', '2021-11', '2021-12']], dtype='datetime64[M]')
```


In [ ]:
np.arange('2021-01', '2022-11', dtype='datetime64[M]')

array(['2021-01', '2021-02', '2021-03', '2021-04', '2021-05', '2021-06',
       '2021-07', '2021-08', '2021-09', '2021-10', '2021-11', '2021-12',
       '2022-01', '2022-02', '2022-03', '2022-04', '2022-05', '2022-06',
       '2022-07', '2022-08', '2022-09', '2022-10'], dtype='datetime64[M]')

### <a name='10'></a> Exercise 80
Using the _np.datetime64()_ function, generate today's date (the date you were doing the exercise).

In [ ]:
np.datetime64('today')

numpy.datetime64('2021-05-27')